[package]
name = "snekcloud-node"
version = "0.1.0"
authors = ["trivernis <trivernis@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vented = "0.1.2"
rusqlite = "0.24.1"
rand = "0.7.3"
base64 = "0.13.0"